In [1]:
import pandas as pd
import plotly.express as px
from statsmodels.tsa.seasonal import seasonal_decompose
import logging
import datetime
import time

from datetime import datetime

from pyspark.sql.functions import col, datediff
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

import calendar
import pandas as pd
import plotly.express as px
from pyspark.sql import SparkSession
from pyspark.sql.functions import concat, col
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from ipywidgets import interact, widgets
from matplotlib.dates import MonthLocator, DateFormatter
import geopandas as gpd
from shapely.geometry import Point
from sklearn.preprocessing import StandardScaler
from statsmodels.tsa.holtwinters import ExponentialSmoothing
import geopandas as gpd
from mpl_toolkits.axes_grid1 import make_axes_locatable
#from fbprophet import Prophet
from sklearn.metrics import mean_squared_error
import numpy as np
import plotly.graph_objects as go
from pyspark.sql import functions as F
from pyspark.sql.functions import year, month
from sklearn.metrics.pairwise import euclidean_distances
from pyspark.sql.functions import year, month, sum as sum_
from scipy.spatial.distance import euclidean
from prophet import Prophet
from pyspark.sql.functions import col, countDistinct , desc , count , length
from pyspark.sql.functions import split, col, when
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, udf, dayofmonth, last_day ,to_date, lit, isnull
from pyspark.sql.types import IntegerType
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error
from dateutil.relativedelta import relativedelta
from pyspark.sql.functions import date_format

from pyspark.sql.functions import col, coalesce, current_date, months_between, round
from pyspark.sql.functions import regexp_replace

import schedule
from pyspark.sql.functions import col, to_timestamp, date_format

import pyspark
import pandas as pd
import boto3
import sagemaker
import sagemaker.feature_store.feature_store as fs
import databricks.connect
from dateutil.relativedelta import relativedelta

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error, mean_absolute_error
from sklearn.metrics import mean_squared_error, root_mean_squared_error

import pandas as pd
import numpy as np
from prophet import Prophet
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
import plotly.graph_objects as go
from itertools import product
import random
import statsmodels.api as sm
import os

from pyspark.sql import functions as F
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, months_between, current_date,expr
from pyspark.sql.functions import col, substr

import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
from databricks.connect import DatabricksSession


# Get spark
spark = databricks.connect.DatabricksSession.builder.getOrCreate()

c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\pydantic\_internal\_fields.py:192: UserWarning: Field name "json" in "MonitoringDatasetFormat" shadows an attribute in parent "Base"
  warnings.warn(

[02/20/25 17:12:53] INFO     Found credentials in shared credentials file: ~/.aws/credentials   ]8;id=811162;file://c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\botocore\credentials.py\credentials.py]8;;\:]8;id=517784;file://c:\Users\gusta\AppData\Local\pypoetry\Cache\virtualenvs\ltv-novo-aF9Dy8BA-py3.10\lib\site-packages\botocore\credentials.py#1278\1278]8;;\

sagemaker.config INFO - Not applying SDK defaults from location: C:\ProgramData\sagemaker\sagemaker\config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: C:\Users\gusta\AppData\Local\sagemaker\sagemaker\config.yaml

In [2]:
spark.conf.set("spark.sql.legacy.timeParserPolicy", "LEGACY")

In [3]:
ltv = spark.table("dev.dw_rok.tb_ltv")

In [4]:
tabela_nova_df = ltv.toPandas()

In [5]:
# Criar a nova tabela eliminando valores nulos da coluna 'hierarquia'
tabela_cnae = tabela_nova_df.dropna(subset=['Hierarquia'])

In [6]:
print(tabela_cnae.isnull().sum())

contratos                                        0
documento                                        0
cliente                                          0
data_inicio                                      0
data_final                                   13472
max_conexao                                  13472
data_primeiro_boleto                             0
data_ultimo_boleto                           13472
boletos_gerados                                  0
total_valor_pago                                 0
receita                                          0
tipo_saida                                       0
meses_contrato                                   0
meses_boleto                                     0
anos_boleto                                      0
anos_contrato                                    0
boleto_gerados_anos                              0
churn                                            0
ano_inicio                                       0
diferenca_meses_inicio_primeiro_boleto           0
diferenca_meses_final_ultimo_boleto              0
classifica_diferenca_boleto_tempo_inicial        0
classifica_diferenca_boleto_tempo_final          0
CNPJ_CPF                                         0
CNAE_RF                                          0
Hierarquia                                       0
uf                                               0
data_inicio_atividade                            0
empresa                                          0
dtype: int64

In [8]:
tabela_cnae[['primeira_hierarquia', 'segunda_hierarquia', 'terceira_hierarquia']] = tabela_cnae['Hierarquia'].str.split(';', n=2, expand=True)

C:\Users\gusta\AppData\Local\Temp\ipykernel_23372\1189948823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_cnae[['primeira_hierarquia', 'segunda_hierarquia', 'terceira_hierarquia']] = tabela_cnae['Hierarquia'].str.split(';', n=2, expand=True)
C:\Users\gusta\AppData\Local\Temp\ipykernel_23372\1189948823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_cnae[['primeira_hierarquia', 'segunda_hierarquia', 'terceira_hierarquia']] = tabela_cnae['Hierarquia'].str.split(';', n=2, expand=True)
C:\Users\gusta\AppData\Local\Temp\ipykernel_23372\1189948823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_cnae[['primeira_hierarquia', 'segunda_hierarquia', 'terceira_hierarquia']] = tabela_cnae['Hierarquia'].str.split(';', n=2, expand=True)

In [9]:
display(tabela_cnae)

,contratos,documento,cliente,data_inicio,data_final,max_conexao,data_primeiro_boleto,data_ultimo_boleto,boletos_gerados,total_valor_pago,...,classifica_diferenca_boleto_tempo_final,CNPJ_CPF,CNAE_RF,Hierarquia,uf,data_inicio_atividade,empresa,primeira_hierarquia,segunda_hierarquia,terceira_hierarquia
0,1,00012212000199,435133,2019-04-12,2019-12-23,0,2019-05-01,2020-01-01,9,436.5,...,0 a 1 mês,00012212000199,4781400,Comércio; Comércio varejista; Vestuário e aces...,SP,19940531,RedeOk,Comércio,Comércio varejista,Vestuário e acessórios
2,1,00071260000158,166252,2006-01-25,2008-06-30,-1,2006-02-01,2008-06-01,21,681.2,...,0 a 1 mês,00071260000158,8640213,Serviços; Saúde,MT,19940519,RedeOk,Serviços,Saúde,None
3,1,00076958000166,436692,2019-06-04,2023-11-22,-1,2019-07-01,2023-11-01,53,3631.6,...,0 a 1 mês,00076958000166,4751201,Comércio; Comércio varejista; Informática e co...,MT,19940526,RedeOk,Comércio,Comércio varejista,Informática e comunicação
4,1,00082998000110,423039,2018-01-18,2018-12-19,0,2018-02-01,2019-03-01,14,910.0,...,2 a 5 meses,00082998000110,2930101,Indústria; Indústrias de Transformação; Automo...,PR,19940606,RedeOk,Indústria,Indústrias de Transformação,Automotores
5,1,00108003000143,392329,2016-05-12,2019-02-28,-1,2016-06-01,2019-02-01,33,3039.0,...,0 a 1 mês,00108003000143,4771701,Comércio; Comércio varejista; Farmacêuticos,TO,19940708,RedeOk,Comércio,Comércio varejista,Farmacêuticos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130219,1,97509277000186,387499,2016-02-05,2021-06-11,-1,2016-03-01,2021-05-01,61,4513.2,...,0 a 1 mês,97509277000186,4771704,Comércio; Comércio varejista; Farmacêuticos,GO,19940428,RedeOk,Comércio,Comércio varejista,Farmacêuticos
130220,1,97519184000132,363428,2014-12-29,2015-06-29,-1,2015-01-01,2015-06-01,6,264.0,...,0 a 1 mês,97519184000132,8291100,Serviços; Serviços Administrativos; Escritório,MG,20110708,RedeOk,Serviços,Serviços Administrativos,Escritório
130221,1,97534145000104,320997,2013-05-18,2016-02-29,-1,2013-06-01,2016-01-01,29,1812.8,...,0 a 1 mês,97534145000104,4646001,Comércio; Comércio atacadista; Cosméticos,PB,20110707,RedeOk,Comércio,Comércio atacadista,Cosméticos
130222,1,97547696000102,298805,2012-04-19,2014-01-15,-1,2012-05-01,2013-12-05,16,374.2,...,0 a 1 mês,97547696000102,9602501,Serviços; Serviços Diversos; Serviços pessoais,PR,20110713,RedeOk,Serviços,Serviços Diversos,Serviços pessoais
130223,1,98042120000660,67870,2002-09-06,2015-01-27,-1,2006-02-01,2006-05-01,3,39.0,...,Maior que 24 meses,98042120000660,4731800,Comércio; Comércio varejista; Combustíveis,RS,19731123,RedeOk,Comércio,Comércio varejista,Combustíveis

In [12]:


# Contando o número de clientes por segmento da primeira hierarquia
contagem_clientes = tabela_cnae.groupby('primeira_hierarquia')['documento'].nunique().reset_index()

# Renomeando as colunas para melhor visualização
contagem_clientes.columns = ['primeira_hierarquia', 'quantidade_clientes']

# Ordenando do maior para o menor
contagem_clientes = contagem_clientes.sort_values(by='quantidade_clientes', ascending=False)
display(contagem_clientes)

  primeira_hierarquia  quantidade_clientes
1            Comércio                84856
3            Serviços                30285
2           Indústria                14536
0        Agropecuária                  309